apiVersion: v1
kind: Service
metadata:
  name: mege-api
  labels:
    app: mege-api
spec:
  type: NodePort
  ports:
    - port: 3001
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: mege-api

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mege-api-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi

---

apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: mege-api
  labels:
    app: mege-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mege-api
  template:
    metadata:
      labels:
        app: mege-api
    spec:
      volumes:
        - name: mege-api-pv-storage
          persistentVolumeClaim:
            claimName: mege-api-pv-claim
      containers:
        - name: mege-api
          image: vunguyenhung/mege-api:d0da3b9
          ports:
            - name: http
              containerPort: 3001
              protocol: TCP
          volumeMounts:
            - mountPath: /usr/.mege/images # This value MUST match with the env var in the config map.
              name: mege-api-pv-storage
          envFrom:
            - configMapRef:
                name: mege-env
          lifecycle:
            postStart:
              exec:
                command: ["bash", "./up.sh"]
            preStop:
              exec:
                command: ["bash", "./down.sh"]
