apiVersion: v1
kind: Service
metadata:
  name: mege-frontend
  labels:
    app: mege-frontend
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: mege-frontend

---

apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: mege-frontend
  labels:
    app: mege-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mege-frontend
  template:
    metadata:
      labels:
        app: mege-frontend
    spec:
      containers:
        - name: mege-frontend
          image: vunguyenhung/mege-frontend:5fb8dcb
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
